version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - datavol:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    hostname: web
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    build:
      context: .
      dockerfile: Dockerfile
    command: mix phx.server
    volumes:
      - .:/blog_app
    ports:
      - "4000:4000"
    depends_on:
      - db
volumes:
  datavol:
