version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - datavol:/var/lib/postgresql/data
    environment:
      BIND-ADDRESS: 0.0.0.0
    ports:
      - "5432:5432"
    tty: true

volumes:
  datavol:
